/**
 * Deploy Service
 *
 * Browser-compatible deployment configuration generator for Lisa.
 * Generates deployment configs for popular cloud platforms that users
 * can download and use with their CLI tools.
 *
 * Adapted from Code Buddy's cloud-configs.ts for browser environments.
 * Supports all 6 Code Buddy platforms plus Vercel and Netlify.
 */

// ============================================================================
// Types
// ============================================================================

export type CloudPlatform =
  | 'fly'
  | 'railway'
  | 'render'
  | 'hetzner'
  | 'northflank'
  | 'gcp'
  | 'vercel'
  | 'netlify';

export interface DeployConfig {
  appName: string;
  platform: CloudPlatform;
  region?: string;
  port?: number;
  env?: Record<string, string>;
  memory?: string;
  cpus?: number;
}

export interface GenerateResult {
  success: boolean;
  files: Array<{ path: string; content: string }>;
  instructions: string;
}

// ============================================================================
// Input Sanitization
// ============================================================================

/**
 * Sanitize an app name to only allow safe characters.
 * Matches Code Buddy's sanitizeAppName pattern.
 */
export function sanitizeAppName(name: string): string {
  if (!/^[a-zA-Z0-9][a-zA-Z0-9_-]*$/.test(name)) {
    throw new Error(
      `Invalid app name "${name}". Only alphanumeric characters, hyphens, and underscores are allowed, and it must start with an alphanumeric character.`
    );
  }
  return name;
}

/**
 * Escape characters dangerous in YAML/TOML string contexts and shell.
 * Matches Code Buddy's sanitizeEnvValue pattern.
 */
export function sanitizeEnvValue(value: string): string {
  return value.replace(/[\\"$`!]/g, '\\$&');
}

// ============================================================================
// Per-Platform Config Generators
// ============================================================================

function generateFlyConfig(config: DeployConfig): GenerateResult {
  const appName = sanitizeAppName(config.appName);
  const port = config.port ?? 3000;
  const region = config.region ?? 'iad';

  const envLines = Object.entries(config.env ?? {})
    .map(([k, v]) => `  ${k} = "${sanitizeEnvValue(v)}"`)
    .join('\n');

  const flyToml = `# Generated by Lisa
app = "${appName}"
primary_region = "${region}"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = ${port}
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[env]
  NODE_ENV = "production"
  PORT = "${port}"
${envLines}

[[vm]]
  memory = "${config.memory ?? '512mb'}"
  cpus = ${config.cpus ?? 1}
`;

  return {
    success: true,
    files: [{ path: 'fly.toml', content: flyToml }],
    instructions: `Deploy with: fly launch --name ${appName} --region ${region}`,
  };
}

function generateRailwayConfig(config: DeployConfig): GenerateResult {
  const railwayJson = JSON.stringify(
    {
      $schema: 'https://railway.app/railway.schema.json',
      build: { builder: 'DOCKERFILE', dockerfilePath: 'Dockerfile' },
      deploy: {
        startCommand: `node dist/index.js`,
        healthcheckPath: '/api/health',
        restartPolicyType: 'ON_FAILURE',
        restartPolicyMaxRetries: 3,
      },
    },
    null,
    2
  );

  const envLines = Object.entries(config.env ?? {})
    .map(([k, v]) => `${k}=${sanitizeEnvValue(v)}`)
    .join('\n');

  const files: Array<{ path: string; content: string }> = [
    { path: 'railway.json', content: railwayJson },
  ];

  if (envLines) {
    files.push({ path: '.env.railway', content: envLines });
  }

  return {
    success: true,
    files,
    instructions: 'Deploy with: railway up',
  };
}

function generateRenderConfig(config: DeployConfig): GenerateResult {
  const appName = sanitizeAppName(config.appName);
  const port = config.port ?? 3000;

  const envVarLines = Object.entries(config.env ?? {})
    .map(([k, v]) => `      - key: ${k}\n        value: "${sanitizeEnvValue(v)}"`)
    .join('\n');

  const renderYaml = `# Generated by Lisa
services:
  - type: web
    name: ${appName}
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "${port}"
${envVarLines}
`;

  return {
    success: true,
    files: [{ path: 'render.yaml', content: renderYaml }],
    instructions: 'Connect your repo on render.com and it will auto-deploy.',
  };
}

function generateHetznerConfig(config: DeployConfig): GenerateResult {
  const appName = sanitizeAppName(config.appName);

  const cloudInit = `#cloud-config
# Generated by Lisa — Hetzner Cloud Init
package_update: true
packages:
  - docker.io
  - docker-compose
  - git

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - git clone https://github.com/your-org/${appName}.git /opt/${appName}
  - cd /opt/${appName} && docker compose up -d
`;

  return {
    success: true,
    files: [{ path: 'hetzner-cloud-init.yml', content: cloudInit }],
    instructions: 'Create a Hetzner server with this cloud-init script as user data.',
  };
}

function generateNorthflankConfig(config: DeployConfig): GenerateResult {
  const appName = sanitizeAppName(config.appName);
  const port = config.port ?? 3000;

  const nfJson = JSON.stringify(
    {
      name: appName,
      description: 'Lisa AI companion',
      type: 'combined',
      services: [
        {
          name: 'web',
          type: 'deployment',
          billing: { deploymentPlan: 'nf-compute-20' },
          buildpack: { builder: 'dockerfile', dockerfilePath: '/Dockerfile' },
          ports: [{ name: 'http', internalPort: port, protocol: 'HTTP' }],
          healthChecks: [{ type: 'http', path: '/api/health', port }],
        },
      ],
    },
    null,
    2
  );

  return {
    success: true,
    files: [{ path: 'northflank.json', content: nfJson }],
    instructions: 'Import this template in Northflank dashboard.',
  };
}

function generateGCPConfig(config: DeployConfig): GenerateResult {
  const appName = sanitizeAppName(config.appName);
  const port = config.port ?? 3000;
  const region = config.region ?? 'us-central1';

  const memoryGb = config.memory
    ? parseFloat(config.memory) / 1024
    : 0.5;

  const envVarLines = Object.entries(config.env ?? {})
    .map(([k, v]) => `  ${k}: "${sanitizeEnvValue(v)}"`)
    .join('\n');

  const appYaml = `# Generated by Lisa — Google Cloud App Engine
runtime: custom
env: flex

service: ${appName}

env_variables:
  NODE_ENV: production
  PORT: "${port}"
${envVarLines}

resources:
  cpu: ${config.cpus ?? 1}
  memory_gb: ${memoryGb}

automatic_scaling:
  min_num_instances: 0
  max_num_instances: 1
`;

  return {
    success: true,
    files: [{ path: 'app.yaml', content: appYaml }],
    instructions: `Deploy with: gcloud app deploy --region=${region}`,
  };
}

function generateVercelConfig(config: DeployConfig): GenerateResult {
  const appName = sanitizeAppName(config.appName);
  const region = config.region ?? 'iad1';

  const envEntries = Object.entries(config.env ?? {}).reduce(
    (acc, [k, v]) => {
      acc[k] = sanitizeEnvValue(v);
      return acc;
    },
    {} as Record<string, string>
  );

  const vercelJson = JSON.stringify(
    {
      name: appName,
      version: 2,
      regions: [region],
      framework: 'vite',
      buildCommand: 'npm run build',
      outputDirectory: 'dist',
      env: {
        NODE_ENV: 'production',
        ...envEntries,
      },
      headers: [
        {
          source: '/assets/(.*)',
          headers: [
            { key: 'Cache-Control', value: 'public, max-age=31536000, immutable' },
          ],
        },
      ],
    },
    null,
    2
  );

  return {
    success: true,
    files: [{ path: 'vercel.json', content: vercelJson }],
    instructions: `Deploy with: vercel --prod\nOr connect your repo at vercel.com for automatic deployments.`,
  };
}

function generateNetlifyConfig(config: DeployConfig): GenerateResult {
  const appName = sanitizeAppName(config.appName);

  const envLines = Object.entries(config.env ?? {})
    .map(([k, v]) => `  ${k} = "${sanitizeEnvValue(v)}"`)
    .join('\n');

  const netlifyToml = `# Generated by Lisa
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
${envLines}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[context.production]
  environment = { NODE_ENV = "production" }
`;

  const siteJson = JSON.stringify(
    {
      name: appName,
    },
    null,
    2
  );

  return {
    success: true,
    files: [
      { path: 'netlify.toml', content: netlifyToml },
      { path: '.netlify/state.json', content: siteJson },
    ],
    instructions: `Deploy with: netlify deploy --prod\nOr connect your repo at app.netlify.com for automatic deployments.`,
  };
}

// ============================================================================
// Platform Generators Map
// ============================================================================

const PLATFORM_GENERATORS: Record<CloudPlatform, (config: DeployConfig) => GenerateResult> = {
  fly: generateFlyConfig,
  railway: generateRailwayConfig,
  render: generateRenderConfig,
  hetzner: generateHetznerConfig,
  northflank: generateNorthflankConfig,
  gcp: generateGCPConfig,
  vercel: generateVercelConfig,
  netlify: generateNetlifyConfig,
};

// ============================================================================
// Deploy Instructions
// ============================================================================

const DEPLOY_INSTRUCTIONS: Record<CloudPlatform, string> = {
  fly: `Fly.io Deployment:
1. Install the Fly CLI: curl -L https://fly.io/install.sh | sh
2. Authenticate: fly auth login
3. Place the generated fly.toml in your project root
4. Run: fly launch (first time) or fly deploy (subsequent)
5. Set secrets: fly secrets set KEY=value
6. Monitor: fly status / fly logs`,

  railway: `Railway Deployment:
1. Install Railway CLI: npm install -g @railway/cli
2. Authenticate: railway login
3. Place the generated railway.json in your project root
4. Run: railway up
5. Set environment variables in the Railway dashboard
6. Monitor: railway status / railway logs`,

  render: `Render Deployment:
1. Place the generated render.yaml in your project root
2. Go to render.com and create a new Blueprint
3. Connect your Git repository
4. Render will auto-detect the render.yaml and deploy
5. Set environment variables in the Render dashboard
6. Auto-deploys on every push to the main branch`,

  hetzner: `Hetzner Cloud Deployment:
1. Install hcloud CLI: brew install hcloud (macOS) or download from GitHub
2. Create an API token in the Hetzner Cloud Console
3. Authenticate: hcloud context create my-project
4. Create a server with the cloud-init script:
   hcloud server create --type cx11 --image ubuntu-22.04 --user-data-from-file hetzner-cloud-init.yml --name my-app
5. The server will automatically install Docker and run your app`,

  northflank: `Northflank Deployment:
1. Go to app.northflank.com
2. Create a new project
3. Import the generated northflank.json as a template
4. Connect your Git repository
5. Configure environment variables in the dashboard
6. Deploy and monitor from the Northflank UI`,

  gcp: `Google Cloud Platform Deployment:
1. Install gcloud CLI: curl https://sdk.cloud.google.com | bash
2. Authenticate: gcloud auth login
3. Set your project: gcloud config set project YOUR_PROJECT_ID
4. Place the generated app.yaml in your project root
5. Deploy: gcloud app deploy
6. Monitor: gcloud app logs tail`,

  vercel: `Vercel Deployment:
1. Install Vercel CLI: npm install -g vercel
2. Authenticate: vercel login
3. Place the generated vercel.json in your project root
4. Deploy: vercel (preview) or vercel --prod (production)
5. Or connect your repo at vercel.com for automatic deployments
6. Set environment variables: vercel env add KEY`,

  netlify: `Netlify Deployment:
1. Install Netlify CLI: npm install -g netlify-cli
2. Authenticate: netlify login
3. Place the generated netlify.toml in your project root
4. Deploy: netlify deploy --prod
5. Or connect your repo at app.netlify.com for automatic deployments
6. Set environment variables: netlify env:set KEY value`,
};

// ============================================================================
// Public API
// ============================================================================

/**
 * Generate deployment configuration files for a given cloud platform.
 */
export function generateDeployConfig(config: DeployConfig): GenerateResult {
  const generator = PLATFORM_GENERATORS[config.platform];
  if (!generator) {
    return {
      success: false,
      files: [],
      instructions: `Unknown platform: ${config.platform}. Supported platforms: ${Object.keys(PLATFORM_GENERATORS).join(', ')}`,
    };
  }

  return generator(config);
}

/**
 * Get detailed CLI deployment instructions for a platform.
 */
export function getDeployInstructions(platform: CloudPlatform): string {
  return DEPLOY_INSTRUCTIONS[platform] ?? `No instructions available for platform: ${platform}`;
}

/**
 * Get the list of all supported cloud platforms.
 */
export function getSupportedPlatforms(): CloudPlatform[] {
  return Object.keys(PLATFORM_GENERATORS) as CloudPlatform[];
}

/**
 * Trigger a browser download of generated deployment config files.
 * Creates a single file download for single-file configs, or a combined
 * text file with all configs for multi-file configs.
 *
 * Uses Blob + URL.createObjectURL + anchor click pattern (browser-compatible).
 */
export function downloadConfig(result: GenerateResult): void {
  if (!result.success || result.files.length === 0) {
    return;
  }

  if (result.files.length === 1) {
    // Single file: download directly
    const file = result.files[0];
    downloadFile(file.path, file.content);
  } else {
    // Multiple files: combine into a single downloadable text
    const combined = result.files
      .map((f) => `# ===== ${f.path} =====\n${f.content}`)
      .join('\n\n');
    const primaryName = result.files[0].path.replace(/\.[^.]+$/, '') + '-bundle.txt';
    downloadFile(primaryName, combined);
  }
}

/**
 * Download individual config files one by one.
 * Useful when the user wants separate files instead of a bundle.
 */
export function downloadConfigFiles(result: GenerateResult): void {
  if (!result.success || result.files.length === 0) {
    return;
  }

  for (const file of result.files) {
    downloadFile(file.path, file.content);
  }
}

/**
 * Trigger a browser download of a single file.
 */
function downloadFile(filename: string, content: string): void {
  // Extract just the filename (strip any directory prefix like ".netlify/")
  const basename = filename.split('/').pop() ?? filename;

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = basename;
  anchor.style.display = 'none';

  document.body.appendChild(anchor);
  anchor.click();

  // Clean up
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}
